application: p2ptraders-app
version: 2
runtime: python27
api_version: 1
threadsafe: false
default_expiration: "5d 12h"
includes:
- navigation.yaml
- profiles.yaml
- campaigns.yaml
- wallet.yaml
- paypal.yaml
- p2ploans.yaml
- affiliates.yaml
- admin.yaml
- social.yaml
- chat.yaml
- CronJobsSchedules.yaml
handlers:

- url: /static
  static_dir: static
- url: /static/bootstrap
  static_dir: static/boostrap

- url: /
  script: main.app
- url: /contact
  script: main.app
- url: /register
  script: main.app
- url: /faq
  script: main.app
- url: /login
  script: main.app
- url: /about
  script: main.app
- url: /terms
  script: main.app
- url: /privacy
  script: main.app

- url: /.*
  script: main.app


libraries:
- name: webapp2
  version: "2.5.2"

- name: jinja2
  version: "latest"

inbound_services:
- mail
- warmup
- channel_presence
